<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>FileVault.UI</RootNamespace>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Using Remove="System.Windows.Forms" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="LibVLCSharp" Version="3.9.3" />
    <PackageReference Include="LibVLCSharp.WPF" Version="3.9.3" />
    <PackageReference Include="MessagePack" Version="3.1.4" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.21" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FileVault.Shared\FileVault.Shared.csproj" />
  </ItemGroup>
</Project>
